apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patchesStrategicMerge:
- cpu-limits-patch.yaml
- node-affinity-patch.yaml
- autoscaling-patch.yaml

configMapGenerator:
- name: env-config
  behavior: merge
  literals:
  - ENVIRONMENT=production
  - FIX_ENDPOINT=fix.prod.quantum:9876

resources:
- prod-ingress.yaml
- certificate-issuer.yaml